### ISSUE TITLE
missing requirements

### ISSUE THREAD

**Issue by mikeyc7m** [guru-digital/frontend-admin#6]
this module also requires "gdmedia/silverstripe-status-message" which uses JsonSerializable - this requires php 5.4, silverstripe 3+ doesn't. i can't use this module on my current php setup.

**Comment by cjsewell** [comment]
I see your point. Are you in a position to submit a pull request to remove the php 5.4 dependency?

**Comment by cjsewell** [comment]
Fixed by https://github.com/guru-digital/frontend-admin/commit/1fdccab11c09d5e04f5e3e904438a6a30ac9ce83 and https://github.com/guru-digital/silverstripe-status-message/commit/34a3f68b1dd6b11088ca121ec5b73a21f1a9f682
